Update to allow users to add thier own Personal Holidays
monkut/kippo pull request #138
Opened 2020-11-20 05:15 UTC by takuw119

2020-11-20 05:20 UTC, monkut requested changes

2020-11-20 05:20 UTC, monkut commented on kippo/accounts/admin.py
> +    def get_form(self, request, obj=None, **kwargs):
Can you write a testcase for this?

Confirm that returned form is as expected:

- case where request is a superuser
- case where request is NOT a superuser

2020-11-20 05:20 UTC, monkut commented on kippo/accounts/admin.py
>      def get_queryset(self, request):
Make a testcase for this too.

Confirm: 

- case where user is superuser
- case where is NOT superuser and NO orginizationmembership
- case where is NOT superuser and HAS organizationalmembership

2020-11-25 08:55 UTC, takuw119 commented on kippo/common/tests.py
> +        # create staff user with no org and related request mock
IsStaffModelAdminTestCaseBaseクラス内に、組織に属していないスタッフユーザーが存在していなかったため、作成しました。

2020-11-25 08:57 UTC, monkut approved these changes

2020-11-25 08:57 UTC, merged