Support float values for estimate
monkut/kippo pull request #139
Opened 2020-12-02 06:12 UTC by takuw119

2020-12-02 06:16 UTC, takuw119 commented
#137

2020-12-02 08:27 UTC, monkut requested changes

2020-12-02 08:27 UTC, monkut commented on kippo/tasks/functions.py
> +            suggested_estimate = int(math.ceil(status.estimate_days)) if status.estimate_days else default_suggested
すみません、この状態でceilしたくないですね。最後のみになります。これなら、現状と結果が変わらないはずですね。

例えば、複数なEstimateがある場合、

Task1.suggested_estimate = 0.2
Task2.suggested_estimate = 0.3
Task3.suggested_estimate = 0.4

の最終的に合計は、1 dayとなってほしいのですが、これだと、合計が3 daysになるようですね。

2020-12-02 08:27 UTC, monkut commented on kippo/tasks/functions.py
> +            suggested_estimate = int(math.ceil(status.estimate_days)) if status.estimate_days else default_suggested
場合によるQluTaskEstimate側での対応が必要かも

https://github.com/monkut/qlu-scheduler

2020-12-02 08:27 UTC, monkut commented on kippo/tasks/tests/test_task_functions.py
> +    def test_is_project_estimate_days_rounded_up(self):
このテストケースか新しいテストケースで下記のようなタスク作って、想定通りに１になることを書いていくれます？

Task1.estimate_days = 0.2
Task2.estimate_days = 0.3
Task3.estimate_days = 0.4

2021-10-08 07:47 UTC, monkut commented
不完全な状態なので、クローズします。

2021-10-08 07:47 UTC, closed without merging